
server:
  port: 8089
#spring:
#  profiles:
#    active: prod
---

server:
  port: 8083
spring:
  profiles: dev
---
server:
  port: 8084
spring:
  profiles: prod
---




#person:
#  lastName: 陈少磊
#  age: 19
#  birth: 2020/08/01
#  boss: true
#  maps: {k1: v1,k2: 12}
#  lists:
#    - lisi
#    - zhouliu
#  dog:
#    name: 小狗
#    age: 12
