spring:
  mail:
    port: 8080
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.mvueproject.mvueproject.pojo
